name: Build, Test, and Publish

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'

    - name: Install dependencies
      run: dotnet restore BookManagement.API/BookManagement.API.csproj

    - name: Build
      run: dotnet build BookManagement.API/BookManagement.API.csproj --configuration Release --no-restore

    - name: Test
      run: dotnet test BookManagement.API/BookManagement.API.csproj --no-build --verbosity normal
